### ISSUE TITLE
Slowdown after holding "reset" for too long

### ISSUE THREAD

**Issue by naveenarun** [LK00100100/KeyboardFallingBlocks#2]
**Describe the bug**
Holding onto the enter key for ~30 seconds during the game causes a drastic drop in framerate.

**To Reproduce**
1. Start game
2. Hold Enter until lag becomes visible

**Expected behavior**
No slowdown when you hold Enter

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
It appears to be a memory leak and/or DOM leak, but I lack the expertise to figure out the issue.

**Comment by LK00100100** [comment]
Wow, that's really weird. I'm going to go crazy figuring this out. Should be a fun afternoon.

**Comment by LK00100100** [comment]
On the bright side, I was able to get a high score of 30 seconds using the slowdown bug 🥇 .

I'll have to do some research into the matter. I'll have some free time during this weekend (Jan 14) or maybe earlier.

**Comment by LK00100100** [comment]
I have an idea on how to fix it. I'm refactoring in preparation for more coding.

**Comment by LK00100100** [comment]
Under the Chrome Debugger, it showed that the "Animation Frame Fired" was done multiple times per Frame (~16ms), which is bad. It's only supposed to be fired once per Frame.

"Animation Frame Fired" is actually the requestAnimationFunction(). The "requestAnimationFunction" tells your browser to draw stuff when the browser can. This function is called in draw.drawingLoop().

When you reset the game rapidly (or even slowly), it appears to allow multiple firings per Frame. I thought the resetGame() would delete these old drawing-loops and create a new drawing-loop. It seems that it creates a lot of drawing-loops.

I just modified a tiny amount of code so there's always one drawing-loop. The bad thing about this is that the main menu is no longer 100% idle due to pointless drawing, but I don't think that's a large problem.
