### ISSUE TITLE
7-piece bag option (allow user to choose # pieces?)

### ISSUE THREAD

**Issue by naveenarun** [LK00100100/KeyboardFallingBlocks#3]
**Is your feature request related to a problem? Please describe.**
A reddit user contacted me asking me to add a 7-piece bag option (which corresponds to classic Tetris).

**Describe the solution you'd like**
A way of being able to adjust the # of pieces in a bag. I prefer this solution over just adding a 7-bag option, since people in the Tetris community tend to be very particular about their own setup - i.e. more customization is better.

**Describe alternatives you've considered**
N/A

**Additional context**
I was going to do this myself but I'm a bit busy atm. I can do it if you want me to, but it will probably be a couple of weeks before I look at it. Let me know if you have time to take it, otherwise I'll do it.

**Comment by LK00100100** [comment]
No problem, I'll look at it right now. I had to rename 7-bag to 14-bag because that's how I really implemented it. I thought if it was a real 7-bag, the preview of pieces would be displayed funny. I think I can fix it real quick.

**Comment by LK00100100** [comment]
I noticed that there was a very subtle bug with my code. The 7-bag was never emptied in-between each game. So I emptied it to ensure a fresh start with each game.

The first piece is never a S or a Z due to that being a bad first piece for the player. If they began with an S or a Z, the player would most likely restart. So I made sure they never get those pieces to begin with. Because of that, you may start with half of a 7-bag in the beginning. This is because I wrote it so the game just keeps drawing until it doesn't get an S or a Z. I figure that no one cares too much about starting with half of a 7-bag at first. Or at least I hope 👍 

So what kind of customization options do you want besides 7-bag?
